changes to UI
elizabeth-phillips/ReadySetRun pull request #34
Opened 2019-04-25 12:54 UTC by shwetarane

added background.

2019-04-25 22:57 UTC, elizabeth-phillips requested changes
I think that the background color is a bit much. Is it possible for a lighter single color(not gradient)?

2019-04-26 13:10 UTC, shwetarane commented
Please merge the existing changes, will change the background in my next Push to UI

2019-04-28 00:39 UTC, elizabeth-phillips approved these changes

2019-04-28 00:42 UTC, merged

2019-04-29 16:21 UTC, shwetarane commented
deleted branch UI